### PR TITLE
Change in the example if scores are not 100

### PR DESCRIPTION
**Pull request by leoafarias**
During my use it seems that the step to fail if scores were not 100 was not working properly. I made an adjustment which is working as expected. Great action by the way. Thanks!

### CODE REVIEW

**Comment by leoafarias** [comment]
Seems like my README.md change broke every on the CI. Seems like it cannot fetch the container. Don't think I can retry.

**Comment by axel-op** [comment]
Can you explain why it didn't work for you? 😊

Also the issues from CI tests come from a major DNS failure with Cloudflare, it is currently affecting many major websites, it's not because of you! I'll re-run them later.

**Comment by axel-op** [comment]
Thanks for this PR by the way, I didn't know we could do such comparisons with floating numbers in the if-condition of a step

**Comment by leoafarias** [comment]
I figured when I saw the cloudflare look up errors. Here is the link to the job that it ran, and it never failed.
https://github.com/leoafarias/fvm/runs/882594226?check_suite_focus=true

Regarding the floating number, I did not test with maintenance, so you might be correct and just caught my typo.

**Comment by axel-op** [comment]
Sorry but what typo 🙃 ?

**Comment by axel-op** [comment]
Oh I see! I'll test that

**Comment by leoafarias** [comment]
Here its a success https://github.com/leoafarias/fvm/runs/882805707?check_suite_focus=true
and here is a failure when I was testing https://github.com/leoafarias/fvm/actions/runs/172961950

Love the hints by the way. Just got tired of getting the pub.dev scores being impacted because of silly mistakes. Also will help contributors. Thanks again!

**Comment by axel-op** [comment]
Since the outputs of this action have changed, following the major new release of Pana, I'm gonna close this pull request. Thanks for creating it!

**Pull request closed without merging**
